# Generated by Django 4.1.1 on 2022-09-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('family', models.CharField(max_length=100)),
                ('id_code', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('gender', models.BooleanField(blank=True, null=True)),
                ('birth_date', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
