# Generated by Django 4.1.1 on 2022-09-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_airline', models.CharField(max_length=100)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('hours', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.BooleanField()),
                ('cobin_class', models.BooleanField()),
                ('price', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField()),
                ('total_price', models.IntegerField()),
                ('remian', models.PositiveIntegerField()),
            ],
        ),
    ]
