# Generated by Django 4.1.1 on 2022-09-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='cobin_class',
            field=models.CharField(blank=True, choices=[('FirstClass', 'FirstClass'), ('SecondClass', 'SecondClass'), ('ThirdClass', 'ThirdClass')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='passenger',
            field=models.CharField(blank=True, choices=[('Adult', 'Adult'), ('Child', 'Child')], max_length=15, null=True),
        ),
    ]
