# Generated by Django 4.1.1 on 2022-09-18 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0004_alter_ticket_cobin_class_alter_ticket_passenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='passenger',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='remian',
        ),
        migrations.AddField(
            model_name='ticket',
            name='passenger_adult',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='passenger_child',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
